services:
  - type: web
    name: Cybercode
    env: ubuntu
    buildCommand: |
      apt-get update && apt-get install -y lua5.3 luarocks redis-server curl python3
      luarocks install luasocket
      luarocks install luasec
      luarocks install redis-lua
      luarocks install dkjson
    startCommand: lua /app/start.lua
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"